### ISSUE TITLE
uncaught exceptions in junit5 tests

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi-test#133]
```
2020-06-11T17:23:53.1081906Z 15044 [pool-4-thread-1] ERROR o.j.j.e.e.JupiterEngineExecutionContext:148 - Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@4daf8903
2020-06-11T17:23:53.1083395Z java.lang.IllegalArgumentException: timeout must be zero or greater
2020-06-11T17:23:53.1084815Z 	at org.osgi.test.common.service.ServiceConfiguration.<init>(ServiceConfiguration.java:63)
2020-06-11T17:23:53.1085938Z 	at org.osgi.test.junit5.service.ServiceExtension.lambda$getServiceUseConfiguration$1(ServiceExtension.java:146)
2020-06-11T17:23:53.1087435Z 	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$0(ExtensionValuesStore.java:81)
2020-06-11T17:23:53.1088786Z 	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:182)
2020-06-11T17:23:53.1090130Z 	at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:58)
2020-06-11T17:23:53.1091344Z 	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:73)
2020-06-11T17:23:53.1092549Z 	at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
2020-06-11T17:23:53.1093709Z 	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:222)
2020-06-11T17:23:53.1095029Z 	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:57)
2020-06-11T17:23:53.1096165Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$9(NodeTestTask.java:151)
2020-06-11T17:23:53.1097328Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.1098440Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:151)
2020-06-11T17:23:53.1099558Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:83)
2020-06-11T17:23:53.1100747Z 	at java.util.ArrayList.forEach(ArrayList.java:1257)
2020-06-11T17:23:53.1103464Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-06-11T17:23:53.1104532Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-06-11T17:23:53.1105816Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.1111818Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-06-11T17:23:53.1118520Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-06-11T17:23:53.1127813Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-06-11T17:23:53.1135743Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.1144203Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-06-11T17:23:53.1151598Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-06-11T17:23:53.1155854Z 	at java.util.ArrayList.forEach(ArrayList.java:1257)
2020-06-11T17:23:53.1167340Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-06-11T17:23:53.1189751Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-06-11T17:23:53.1198800Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.1208018Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-06-11T17:23:53.1214900Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-06-11T17:23:53.1245641Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-06-11T17:23:53.1255434Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.1263975Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-06-11T17:23:53.1271678Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-06-11T17:23:53.1283106Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2020-06-11T17:23:53.1293874Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2020-06-11T17:23:53.1302234Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2020-06-11T17:23:53.1309781Z 	at org.junit.platform.testkit.engine.EngineTestKit.execute(EngineTestKit.java:189)
2020-06-11T17:23:53.1316787Z 	at org.junit.platform.testkit.engine.EngineTestKit.access$100(EngineTestKit.java:54)
2020-06-11T17:23:53.1325837Z 	at org.junit.platform.testkit.engine.EngineTestKit$Builder.execute(EngineTestKit.java:343)
2020-06-11T17:23:53.1335766Z 	at org.osgi.test.junit5.service.AbstractServiceExtensionTest.assertThatTest(AbstractServiceExtensionTest.java:126)
2020-06-11T17:23:53.1347349Z 	at org.osgi.test.junit5.service.AbstractServiceExtensionTest.lambda$futureAssertThatTest$0(AbstractServiceExtensionTest.java:113)
2020-06-11T17:23:53.1353191Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-06-11T17:23:53.1362322Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2020-06-11T17:23:53.1372502Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2020-06-11T17:23:53.1380238Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-06-11T17:23:53.1387473Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-06-11T17:23:53.1391941Z 	at java.lang.Thread.run(Thread.java:748)
2020-06-11T17:23:53.1809645Z 15121 [pool-7-thread-1] ERROR o.j.j.e.e.JupiterEngineExecutionContext:148 - Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@1df1ebcc
2020-06-11T17:23:53.1811365Z java.lang.IllegalArgumentException: cardinality must be zero or greater
2020-06-11T17:23:53.1812232Z 	at org.osgi.test.common.service.ServiceConfiguration.<init>(ServiceConfiguration.java:58)
2020-06-11T17:23:53.1814089Z 	at org.osgi.test.junit5.service.ServiceExtension.lambda$getServiceUseConfiguration$1(ServiceExtension.java:146)
2020-06-11T17:23:53.1815141Z 	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$0(ExtensionValuesStore.java:81)
2020-06-11T17:23:53.1816131Z 	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:182)
2020-06-11T17:23:53.1817124Z 	at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:58)
2020-06-11T17:23:53.1818093Z 	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:73)
2020-06-11T17:23:53.1819375Z 	at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
2020-06-11T17:23:53.1820249Z 	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:222)
2020-06-11T17:23:53.1821131Z 	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:57)
2020-06-11T17:23:53.1822009Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$9(NodeTestTask.java:151)
2020-06-11T17:23:53.1823249Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.1824170Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:151)
2020-06-11T17:23:53.1825251Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:83)
2020-06-11T17:23:53.1826044Z 	at java.util.ArrayList.forEach(ArrayList.java:1257)
2020-06-11T17:23:53.1827005Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-06-11T17:23:53.1828039Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-06-11T17:23:53.1829011Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.1829959Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-06-11T17:23:53.1830833Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-06-11T17:23:53.1831769Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-06-11T17:23:53.1832719Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.1833830Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-06-11T17:23:53.1834714Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-06-11T17:23:53.1835486Z 	at java.util.ArrayList.forEach(ArrayList.java:1257)
2020-06-11T17:23:53.1836386Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-06-11T17:23:53.1837396Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-06-11T17:23:53.1838467Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.1839608Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-06-11T17:23:53.1840460Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-06-11T17:23:53.1841346Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-06-11T17:23:53.1842536Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.1843405Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-06-11T17:23:53.1844269Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-06-11T17:23:53.1845262Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2020-06-11T17:23:53.1846237Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2020-06-11T17:23:53.1920709Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2020-06-11T17:23:53.1921689Z 	at org.junit.platform.testkit.engine.EngineTestKit.execute(EngineTestKit.java:189)
2020-06-11T17:23:53.1922629Z 	at org.junit.platform.testkit.engine.EngineTestKit.access$100(EngineTestKit.java:54)
2020-06-11T17:23:53.1923821Z 	at org.junit.platform.testkit.engine.EngineTestKit$Builder.execute(EngineTestKit.java:343)
2020-06-11T17:23:53.1924729Z 	at org.osgi.test.junit5.service.AbstractServiceExtensionTest.assertThatTest(AbstractServiceExtensionTest.java:126)
2020-06-11T17:23:53.1925878Z 	at org.osgi.test.junit5.service.AbstractServiceExtensionTest.lambda$futureAssertThatTest$0(AbstractServiceExtensionTest.java:113)
2020-06-11T17:23:53.1946280Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-06-11T17:23:53.1947273Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2020-06-11T17:23:53.1948272Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2020-06-11T17:23:53.1949132Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-06-11T17:23:53.1949960Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-06-11T17:23:53.1950679Z 	at java.lang.Thread.run(Thread.java:748)
2020-06-11T17:23:53.6420972Z 15587 [ool-11-thread-1] ERROR o.j.j.e.e.JupiterEngineExecutionContext:148 - Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@7100b8f1
2020-06-11T17:23:53.6422731Z org.osgi.framework.InvalidSyntaxException: Filter ended abruptly: (&(objectClass=org.osgi.test.junit5.types.Foo)(foo=baz)
2020-06-11T17:23:53.6423893Z 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse(FilterImpl.java:1378)
2020-06-11T17:23:53.6424933Z 	at org.eclipse.osgi.internal.framework.FilterImpl.newInstance(FilterImpl.java:180)
2020-06-11T17:23:53.6425937Z 	at org.eclipse.osgi.internal.framework.FilterImpl.newInstance(FilterImpl.java:176)
2020-06-11T17:23:53.6427372Z 	at org.osgi.framework.FrameworkUtil.createFilter(FrameworkUtil.java:72)
2020-06-11T17:23:53.6428342Z 	at org.osgi.test.common.exceptions.FunctionWithException.lambda$orElseThrow$0(FunctionWithException.java:21)
2020-06-11T17:23:53.6429221Z 	at org.osgi.test.common.filter.Filters.format(Filters.java:43)
2020-06-11T17:23:53.6430093Z 	at org.osgi.test.common.service.ServiceConfiguration.<init>(ServiceConfiguration.java:53)
2020-06-11T17:23:53.6431460Z 	at org.osgi.test.junit5.service.ServiceExtension.lambda$getServiceUseConfiguration$1(ServiceExtension.java:146)
2020-06-11T17:23:53.6432777Z 	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$0(ExtensionValuesStore.java:81)
2020-06-11T17:23:53.6433911Z 	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:182)
2020-06-11T17:23:53.6435472Z 	at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:58)
2020-06-11T17:23:53.6436612Z 	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:73)
2020-06-11T17:23:53.6437918Z 	at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
2020-06-11T17:23:53.6439091Z 	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:222)
2020-06-11T17:23:53.6440262Z 	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:57)
2020-06-11T17:23:53.6441534Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$9(NodeTestTask.java:151)
2020-06-11T17:23:53.6442832Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.6443891Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:151)
2020-06-11T17:23:53.6445548Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:83)
2020-06-11T17:23:53.6446707Z 	at java.util.ArrayList.forEach(ArrayList.java:1257)
2020-06-11T17:23:53.6451087Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-06-11T17:23:53.6454086Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-06-11T17:23:53.6456329Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.6460064Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-06-11T17:23:53.6461396Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-06-11T17:23:53.6464189Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-06-11T17:23:53.6466732Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.6469656Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-06-11T17:23:53.6472310Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-06-11T17:23:53.6473972Z 	at java.util.ArrayList.forEach(ArrayList.java:1257)
2020-06-11T17:23:53.6478322Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-06-11T17:23:53.6481642Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-06-11T17:23:53.6484175Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.6487086Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-06-11T17:23:53.6489080Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-06-11T17:23:53.6493654Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-06-11T17:23:53.6527240Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-06-11T17:23:53.6529803Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-06-11T17:23:53.6532661Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-06-11T17:23:53.6536534Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2020-06-11T17:23:53.6539352Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2020-06-11T17:23:53.6542320Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2020-06-11T17:23:53.6544245Z 	at org.junit.platform.testkit.engine.EngineTestKit.execute(EngineTestKit.java:189)
2020-06-11T17:23:53.6546908Z 	at org.junit.platform.testkit.engine.EngineTestKit.access$100(EngineTestKit.java:54)
2020-06-11T17:23:53.6550043Z 	at org.junit.platform.testkit.engine.EngineTestKit$Builder.execute(EngineTestKit.java:343)
2020-06-11T17:23:53.6552658Z 	at org.osgi.test.junit5.service.AbstractServiceExtensionTest.assertThatTest(AbstractServiceExtensionTest.java:126)
2020-06-11T17:23:53.6556662Z 	at org.osgi.test.junit5.service.AbstractServiceExtensionTest.lambda$futureAssertThatTest$0(AbstractServiceExtensionTest.java:113)
2020-06-11T17:23:53.6558905Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-06-11T17:23:53.6561702Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2020-06-11T17:23:53.6564965Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2020-06-11T17:23:53.6567344Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-06-11T17:23:53.6569511Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-06-11T17:23:53.6571205Z 	at java.lang.Thread.run(Thread.java:748)
2020-06-11T17:23:53.6573020Z Caused by: java.lang.ArrayIndexOutOfBoundsException: 55
2020-06-11T17:23:53.6576495Z 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_and(FilterImpl.java:1445)
2020-06-11T17:23:53.6579165Z 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filtercomp(FilterImpl.java:1420)
2020-06-11T17:23:53.6581901Z 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filter(FilterImpl.java:1397)
2020-06-11T17:23:53.6584567Z 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse(FilterImpl.java:1376)
2020-06-11T17:23:53.6585347Z 	... 52 common frames omitted
```

I am not sure if these are expected or an error. If expected, we should try to get them not to appear in the build output.

**Comment by rotty3000** [comment]
that last exception is odd:
```
10226 [ool-16-thread-1] ERROR o.j.j.e.e.JupiterEngineExecutionContext:148 - Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@20bb6a97
org.osgi.framework.InvalidSyntaxException: Filter ended abruptly: (&(objectClass=org.osgi.test.junit5.types.Foo)(foo=baz)
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse(FilterImpl.java:1378)
	at org.eclipse.osgi.internal.framework.FilterImpl.newInstance(FilterImpl.java:180)
	at org.eclipse.osgi.internal.framework.FilterImpl.newInstance(FilterImpl.java:176)
	at org.osgi.framework.FrameworkUtil.createFilter(FrameworkUtil.java:72)
	at org.osgi.test.common.exceptions.FunctionWithException.lambda$orElseThrow$0(FunctionWithException.java:21)
	at org.osgi.test.common.filter.Filters.format(Filters.java:43)
	at org.osgi.test.common.service.ServiceConfiguration.<init>(ServiceConfiguration.java:53)
	at org.osgi.test.junit5.service.ServiceExtension.lambda$getServiceUseConfiguration$1(ServiceExtension.java:146)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$0(ExtensionValuesStore.java:81)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:182)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:58)
	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:73)
```

Shouldn't the memoize have been initialized? Wouldn't not having been initialized indicate that it shouldn't be created just to be destroyed?

**Comment by rotty3000** [comment]
Specifically, the scenario for that test was that initial configuration was bad. Shouldn't that be reflected somehow in the teardown?

**Comment by rotty3000** [comment]
thirdly, I'm not sure if it's only me, but in the cli these exceptions do not result in failures. I get:
```
Test run finished after 10004 ms
[        58 containers found      ]
[         0 containers skipped    ]
[        58 containers started    ]
[         0 containers aborted    ]
[        58 containers successful ]
[         0 containers failed     ]
[       137 tests found           ]
[         0 tests skipped         ]
[       137 tests started         ]
[         0 tests aborted         ]
[       137 tests successful      ]
[         0 tests failed          ]
```
However, in Eclipse I get:
```
![Screenshot from 2020-06-11 16-17-19](https://user-images.githubusercontent.com/146764/84435035-1117bd00-abff-11ea-92a8-a9db2da81c6e.png)

**Comment by kriegfrj** [comment]
@bjhargrave: Executive Summary is that those stack traces are expected.

Detail: Note that they all start off like this:

> 2020-06-11T17:23:53.1309781Z 	at org.junit.platform.testkit.engine.EngineTestKit.execute(EngineTestKit.java:189)
> 2020-06-11T17:23:53.1316787Z 	at org.junit.platform.testkit.engine.EngineTestKit.access$100(EngineTestKit.java:54)
> 2020-06-11T17:23:53.1325837Z 	at org.junit.platform.testkit.engine.EngineTestKit$Builder.execute(EngineTestKit.java:343)
> 2020-06-11T17:23:53.1335766Z 	at org.osgi.test.junit5.service.AbstractServiceExtensionTest.assertThatTest(AbstractServiceExtensionTest.java:126)
> 2020-06-11T17:23:53.1347349Z 	at org.osgi.test.junit5.service.AbstractServiceExtensionTest.lambda$futureAssertThatTest$0(AbstractServiceExtensionTest.java:113)
> 2020-06-11T17:23:53.1353191Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 2020-06-11T17:23:53.1362322Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 2020-06-11T17:23:53.1372502Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 2020-06-11T17:23:53.1380238Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 2020-06-11T17:23:53.1387473Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

They are generated by these tests:
https://github.com/osgi/osgi-test/blob/272d362bf7a8cd8c2adbf696b4a42838fec09aa9/org.osgi.test.junit5/src/test/java/org/osgi/test/junit5/service/ServiceExtensionTest.java#L195-L201

https://github.com/osgi/osgi-test/blob/272d362bf7a8cd8c2adbf696b4a42838fec09aa9/org.osgi.test.junit5/src/test/java/org/osgi/test/junit5/service/ServiceExtensionTest.java#L213-L214

https://github.com/osgi/osgi-test/blob/272d362bf7a8cd8c2adbf696b4a42838fec09aa9/org.osgi.test.junit5/src/test/java/org/osgi/test/junit5/service/ServiceExtensionTest.java#L230-L231

Each of these tests have the following structure:

1. Start with a dummy test class with a misconfigured `@InjectService` annotation.
2. Run the test class in Jupiter using EngineTestKit (scheduled to run in the executor).
3. Assert that the result throws the expected exception.

So I need to pass in the right parameters to `JupiterTestEngine` in the `EngineTestKit` run to suppress the logging to the console.

**Comment by kriegfrj** [comment]
> that last exception is odd:
> 
> Shouldn't the memoize have been initialized? Wouldn't not having been initialized indicate that it shouldn't be created just to be destroyed?
>
> Specifically, the scenario for that test was that initial configuration was bad. Shouldn't that be reflected somehow in the teardown?

Forgive me @rotty3000 , I'm not sure that I follow here? Does my response to @bjhargrave shed any light on this for you? If not, I'm not quite sure that I've understood your point (or more precisely, I should say that I'm quite sure I have *not* understood your point :smile:). One thing that I am fairly sure about though is that this issue is probably different to the one that prompted @bjhargrave to raise this issue.

**Comment by kriegfrj** [comment]
> thirdly, I'm not sure if it's only me, but in the cli these exceptions do not result in failures. I get:
> 

As the exceptions are expected behaviour, they should not result in failures in the CLI *or* in Eclipse. 

The Eclipse test that is failing in your screenshot is a legitimate problem, but completely different to the OP (which was a problem with the tests for `ServiceExtension`, while yours in the screenshot was a problem with tests for `BundleContextExtension`). I have not seen that behaviour before - if you see it again, next time can you cut-and-past the failure stack trace(s) for the failing test(s) and I'll try and investigate.

**Comment by rotty3000** [comment]
it's fine, there is nothing overly important in my comments, just adding observations. Feel free to ignore them.
